easy_admin:
    entities:
        Annonces:
            class: App\Entity\Annonces
#form:
#   fields:
#      - name
#     - description
#    - price
#   - isPublished
#   - imageName
#   - categories
#   - author
#   - tags
#list:
#   fields: [name,isPublished, categories, author]
        Categories:
            class: App\Entity\Categories
        User:
            class: App\Entity\User
    site_name: Administration Broc
