vich_uploader:
    db_driver: orm

    mappings:
        annonces_images:
            uri_prefix: /img/annonces
            upload_destination: '%kernel.project_dir%/public/img/annonces'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
